-- Таблиця для Нотаток
CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT,
    priority VARCHAR(20),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
    );

-- Таблиця для Аудиту (для демонстрації JdbcClient та транзакцій)
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(100) NOT NULL,
    note_id BIGINT,
    timestamp TIMESTAMP
    );