spring.application.name=notepad

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require

spring.datasource.username=postgres.dkkqyqilcwwydyqxfskb

spring.datasource.password=Hcnvml2hyOfV9yj3

spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

# Hibernate ??? ????????/??????? ???????, ???? ?? ??????? ????????
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL, ???? ??????? Hibernate (??? ????????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??????? ??? PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect